package com.tweetapp.entity;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

//@Document(collection =  "tweets")
@DynamoDBTable(tableName = "Tweets")
@ApiModel(value = "Model object that stores the Tweet information")
public class Tweet implements Comparable<Tweet> {

	@ApiModelProperty(notes = "Id of the Tweet") 
	//@Id
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@ApiModelProperty(notes = "Tweet message of the Tweet")
	@NotEmpty(message = "Tweet message cannot be empty")
	@Size(max = 144,message = "Tweet message should not be greater than 144 characters")
	@DynamoDBAttribute
	private String tweet;
	
	@ApiModelProperty(notes = "Tweet creation Date")
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
	private LocalDateTime postedDate;
	
	@ApiModelProperty(notes = "Likes of the Tweet")
	@DynamoDBAttribute
	private long likes;
	
	@ApiModelProperty(notes = "Liked users of the Tweet")
	@DynamoDBAttribute
	private List<String> likedBy;
	
	@ApiModelProperty(notes = "Replies of the Tweet")
	@DynamoDBAttribute
	private List<Tweet> replies;
	
	@ApiModelProperty(notes = "Tag of the Tweet")
	@Size(max = 50,message = "TweetTag should not be greater than 50 characters")
	@DynamoDBAttribute
	private String tweetTag;
	
	@ApiModelProperty(notes = "User of the Tweet")
	@DynamoDBAttribute
	private String user;
	
	public Tweet() {}

	public Tweet(String id, String tweet, LocalDateTime postedDate, long likes, List<String> likedBy,
			List<Tweet> replies, String tweetTag, String user) {
		super();
		this.id = id;
		this.tweet = tweet;
		this.postedDate = postedDate;
		this.likes = likes;
		this.likedBy = likedBy;
		this.replies = replies;
		this.tweetTag = tweetTag;
		this.user = user;
	}



	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTweet() {
		return tweet;
	}

	public void setTweet(String tweet) {
		this.tweet = tweet;
	}

	public LocalDateTime getPostedDate() {
		return postedDate;
	}

	public void setPostedDate(LocalDateTime postedDate) {
		this.postedDate = postedDate;
	}

	public long getLikes() {
		return likes;
	}

	public void setLikes(long likes) {
		this.likes = likes;
	}

	public List<Tweet> getReplies() {
		return replies;
	}

	public void setReplies(List<Tweet> replies) {
		this.replies = replies;
	}

	public String getTweetTag() {
		return tweetTag;
	}

	public void setTweetTag(String tweetTag) {
		this.tweetTag = tweetTag;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public List<String> getLikedBy() {
		return likedBy;
	}

	public void setLikedBy(List<String> likedBy) {
		this.likedBy = likedBy;
	}

	@Override
	public String toString() {
		return "Tweet{" +
				"id='" + id + '\'' +
				", tweet='" + tweet + '\'' +
				", postedDate=" + postedDate +
				", likes=" + likes +
				", likedBy=" + likedBy +
				", replies=" + replies +
				", tweetTag='" + tweetTag + '\'' +
				", user='" + user + '\'' +
				'}';
	}

	@Override
	public int compareTo(Tweet tweet1) {
		return this.getPostedDate().compareTo(tweet1.getPostedDate());
	}

	static public class LocalDateTimeConverter implements DynamoDBTypeConverter<String, LocalDateTime> {
		@Override
		public String convert( final LocalDateTime time ) {
			return time.toString();
		}
		@Override
		public LocalDateTime unconvert( final String stringValue ) {
			return LocalDateTime.parse(stringValue);
		}
	}
}
