version: 1
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Entered build phase"
      - cd TweetAppBackend
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/tweetappbackend .
      
      - docker tag service/tweetappbackend 402760915525.dkr.ecr.us-east-2.amazonaws.com/tweet-app-backend-repo:tweetappbackend
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 402760915525.dkr.ecr.us-east-2.amazonaws.com/tweet-app-backend-repo:tweetappbackend
    - printf '[{"name":"tweetappbackend-container","imageUri":"%s"}]' 402760915525.dkr.ecr.us-east-2.amazonaws.com/tweet-app-backend-repo:tweetappbackend > taskdefinition.json
artifacts:
  files:
    - TweetAppBackend/taskdefinition.json